export const MOVIES = [
  {
    "Title": "Kushi",
    "Release Date": "2001-04-27",
    "id": 1
  }, {
    "Title": "Srimanthudu",
    "Release Date": "2015-08-07",
    "id": 2
  }, {
    "Title": "Race Gurram",
    "Release Date": "2014-12-18",
    "id": 3
  },
  {
    "Title": "Manam",
    "Release Date": "2009-02-13",
    "id": 4
  },
  {
    "Title": "Mirchi",
    "Release Date": "2018-10-12",
    "id": 5
  },
  {
    "Title": "Mahanati",
    "Release Date": "2018-05-09",
    "id": 6
  },
  {
    "Title": "Rangasthalam",
    "Release Date": "2018-03-30",
    "id": 7
  },
  {
    "Title": "Jersey",
    "Release Date": "2013-05-19",
    "id": 8
  }, {
    "Title": "Arjun Reddy",
    "Release Date": "2017-08-25",
    "id": 9
  },
  {
    "Title": "Janatha Garage",
    "Release Date": "2016-09-01",
    "id": 10
  },
  {
    "Title": "Oopiri",
    "Release Date": "2016-03-25",
    "id": 11
  }
]


export const KEYWORDS = ["Adhurs",
  "Leader",
  "Prasthanam",
  "Darling",
  "Jersey",
  "Vedam",
  "Golimar",
  "Sneha Geetham",
  "Maryada Ramanna",
  "Khaleja",
  "Brindaavanam",
  "Rangasthalam",
  "Yemaindi Ee Vela",
  "Orange",
  "Ala Modalaindi",
  "Gaganam",
  "Mr Perfect",
  "Nenu Naa Rakshasi",
  "100% Love",
  "Virodhi",
  "Dookudu",
  "Oosaravelli",
  "Pilla Zamindar",
  "Mahanati",
  "Sri Rama Rajyam",
  "Solo",
  "Business Man",
  "Ishq",
  "Eega",
  "Julayi",
  "Andala Rakshasi",
  "Routine Love Story",
  "Krishnam Vande Jagadgurum",
  "Yeto Vellipoyindhi Manasu",
  "Mithunam",
  "Nenjamellam Pala Vannam",
  "Mirchi",
  "Swamy Ra Ra",
  "Prema Katha Chitram",
  "Mallela Theeramlo Sirimalle Puvvu",
  "Sahasam",
  "Anthaka Mundu Aa Tarvatha",
  "Venkatadri Express",
  "Prema Ishq Kaadhal",
  "Uyyala Jampala",
  "1: Nenokkadine",
  "Yevadu",
  "Race Gurram",
  "Chandamama Kathalu",
  "Prathinidhi",
  "Manam",
  "Oohalu Gusagusalade",
  "Drushyam",
  "Run Raja Run",
  "Anukshanam",
  "Karthikeya",
  "Rowdy Fellow",
  "Pataas",
  "Malli Malli Idi Rani Roju",
  "Temper",
  "Yevade Subramanyam",
  "Asura",
  "Baahubali: The Beginning",
  "Srimanthudu",
  "Bhale Bhale Magadivoy",
  "Kanche",
  "Kumari 21F",
  "Bhale Manchi Roju",
  "To Father with Love",
  "Krishna Gaadi Veera Prema Gaadha",
  "Kshanam",
  "Guntur Talkies",
  "Kalyana Vaibhogame",
  "Oopiri",
  "Supreme",
  "Anirudh",
  "Gentleman",
  "Oka Manasu",
  "A Aa",
  "Pelli Choopulu",
  "All of Us",
  "Janatha Garage",
  "Jyo Achyutananda",
  "Ekkadiki Pothavu Chinnavada",
  "Dhruva",
  "Vangaveeti",
  "Appatlo Okadundevadu",
  "Premam",
  "Gautamiputra Satakarni",
  "Shatamanam Bhavati",
  "The Ghazi Attack",
  "Guru",
  "Kushi",
  "Baahubali 2: The Conclusion",
  "Keshava",
  "Ami Tumi",
  "Ninnu Kori",
  "Fidaa",
  "Anando Brahma",
  "Nene Raju Nene Mantri",
  "Arjun Reddy",
  "Raja the Great",
  "PSV Garuda Vega",
  "Mental Madhilo"]